import "./globals.css";
import { Suspense } from "react";
import { ThemeProvider } from "./lib/ThemeProvider";
import Loading from "./loading";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-light-main dark:bg-dark-main">
        <div id="root">
          <ThemeProvider>
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </ThemeProvider>
        </div>
        <script
          type="module"
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
        ></script>
        <script
          nomodule
          src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
        ></script>
      </body>
    </html>
  );
}
