import Header from "./components/Header/Header";
import "./globals.css";
import { ThemeProvider } from "./lib/ThemeProvider";
import { UserProvider } from "@auth0/nextjs-auth0/client";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider>
        <UserProvider>
          <body className="bg-light-main dark:bg-dark-main">
            <Header />
            <div id="root">{children}</div>

            <script
              type="module"
              src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
            ></script>
            <script
              nomodule
              src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
            ></script>
          </body>
        </UserProvider>
      </ThemeProvider>
    </html>
  );
}
